apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: test-workflow

on:
  push:
    branches:
      - 'test'

jobs:
  jenkins-run-job-without-output:
    steps:
      - id: jenkins
        name: invoke-jenkins-job
        uses: cloudbees-io/jenkins-run-job@v2
        with:
          url: https://c1.saas-preprod.beescloud.com/
          username: cloudbees
          token: ND7TD5zU0k9XQRYGRg2N
          job-name: stepstest
