apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Build and deploy

on:
  push:
    branches:
      - "**"


permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build-publish:
    outputs:
      chart: ${{ steps.package.outputs.chart }}
      version: ${{ steps.package.outputs.version }}
    steps:
      - name: Get source code
        uses: cloudbees-io/checkout@v1

      - id: build
        name: Build and scan
        uses: https://github.com/calculi-corp/cb-internal-shared-actions/build@v3
        with:
          run-unit-test: "true"
          unit-test-percent: "70"
          snyk-sast-scan-code: "true"
          go-binary-build: "true"
          kaniko-build: "true"
          trivy-scan-container: "false"
          bundled-sonar-scan: "true"
          registry-type: "ECR"
          snyk-org-name: ${{ vars.SNYK_SAAS_ORG_NAME }}
          snyk-saas-token: ${{ secrets.SNYK_SAAS_TOKEN }}
          go-binary-name: ${{ env.application_name }}
          registry-url: ${{ vars.STAGING_ECR_REGISTRY }}
          registry-image-name: ${{ vars.workflow_execution_env == 'production' && format('services/{0}', env.application_name) || format('throwaway/services/{0}', env.application_name) }}
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}
          dockerfile-path: Dockerfile
          sonarqube-threshold-critical: 0
          sonarqube-threshold-very-high: 1
          sonarqube-threshold-high: 1
          sonarqube-threshold-medium: 2
          sonarqube-threshold-low: 0


      - id: package
        name: Package the helm chart
        uses: https://github.com/calculi-corp/cb-internal-shared-actions/package@v3
        with:
          helm-lint: "true"
          registry-url: ${{ vars.STAGING_ECR_REGISTRY }}
          registry-image-name: ${{ vars.workflow_execution_env == 'production' && 'service-charts' || 'throwaway/service-charts' }}
          helm-package-folder-path: ./charts/${{ env.application_name }}
          values: |
            base:
              image:
                tag: ${{ steps.build.outputs.tag-digest }}

  publish-consul:
    if: ${{ vars.workflow_execution_env == 'production' }}
    outputs:
      name: ${{ steps.consulservicename.outputs.name }}
    steps:
      - id: consulservicename
        name: Generate consul service name for the application
        uses: docker://alpine:3.18
        run: |
          if [ '${{ cloudbees.scm.branch }}' = main ]; then
            printf %s ${{ env.application_name }} > $CLOUDBEES_OUTPUTS/name
          else
            name=$(printf %s-%s ${{ env.application_name }}  ${{ cloudbees.scm.sha }})
            printf %s "$name" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/' > $CLOUDBEES_OUTPUTS/name
          fi

  # splitting db-service dependency to its own action, which saves about 2 mins
  deploy-db-dependencies:
    if: ${{ vars.workflow_execution_env == 'production' && cloudbees.scm.branch != 'main'}}
    steps:
      - id: install-dependencies
        name: Install $application_name dependencies helm charts
        uses: ./actions/dependencies/db
        with:
          registry: ${{ vars.staging_image_registry }}
          chart-registry: ${{ vars.staging_chart_registry }}
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}
          cluster-name: ${{ vars.staging_east_cluster_name }}

  deploy-nats-dependencies:
    if: ${{ vars.workflow_execution_env == 'production' && cloudbees.scm.branch != 'main'}}
    steps:
      - id: install-dependencies
        name: Install $application_name dependencies helm charts
        uses: ./actions/dependencies/nats
        with:
          chart-registry: ${{ vars.staging_chart_registry }}
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}
          cluster-name: ${{ vars.staging_east_cluster_name }}

  deploy-us-east-1:
    if: ${{ vars.workflow_execution_env == 'production' }}
    needs: [build-publish, deploy-nats-dependencies, deploy-db-dependencies, publish-consul]
    steps:
      - id: install-chart
        name: Install $application_name helm chart us-east-1
        uses: ./actions/deploy
        with:
          chart-location:  ${{ needs.build-publish.outputs.chart }}
          version:  ${{ needs.build-publish.outputs.version }}
          release-name: ${{ env.application_name }}
          chart-registry: ${{ vars.staging_chart_registry }}
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}
          cluster-name: ${{ vars.staging_east_cluster_name }}
          aws-region: "us-east-1"
          nats-username: ${{ secrets.NATS_USERNAME }}
          nats-password: ${{ secrets.NATS_PASSWORD }}
          registry: ${{ vars.staging_image_registry }}
          consul-name: ${{ needs.publish-consul.outputs.name }}
          insights-plugin-secret-key: ${{ secrets.INSIGHTS_PLUGIN_SECRET_KEY }}
          datadog-env: ${{ vars.dd_target_env }}
          service-name: ${{ env.application_name }}
          enable-datadog-labels: ${{ cloudbees.scm.branch == 'main' && 'true' || 'false' }}

      - id: uninstall-chart
        name: Uninstall $application_name helm chart us-east-1
        if: ${{ cloudbees.scm.branch != 'main' }}
        uses: ./actions/cleanup
        with:
          release-name:  ${{ env.application_name }}
          namespace:  ${{ steps.install-chart.outputs.namespace }}

  deploy-us-west-2:
    if: ${{ vars.workflow_execution_env == 'production' && cloudbees.scm.branch == 'main' }}
    needs: [ build-publish, publish-consul ]
    steps:
      - name: Login to AWS us-east-1 ECR registry
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.oidc_staging_iam_role }}
          role-duration-seconds: "3600" # optionally set the duration of the login token

      - name: Configure container registry for Staging ECR us-east-1
        uses: cloudbees-io/configure-ecr-credentials@v1

      - id: install-chart
        name: Install $application_name helm chart in us-west-2
        uses: ./actions/deploy
        with:
          chart-location: ${{ needs.build-publish.outputs.chart }}
          version: ${{ needs.build-publish.outputs.version }}
          release-name: ${{ env.application_name }}
          chart-registry: ${{ vars.staging_chart_registry }}
          oidc-iam-role: ${{ vars.oidc_staging_iam_role }}
          cluster-name: ${{ vars.staging_west_cluster_name }}
          aws-region: "us-west-2"
          nats-username: ${{ secrets.NATS_USERNAME }}
          nats-password: ${{ secrets.NATS_PASSWORD }}
          registry: ${{ vars.staging_image_registry }}
          consul-name: ${{ needs.publish-consul.outputs.name }}
          insights-plugin-secret-key: ${{ secrets.INSIGHTS_PLUGIN_SECRET_KEY }}
          datadog-env: ${{ vars.dd_target_env }}
          service-name: ${{ env.application_name }}
          enable-datadog-labels: ${{ cloudbees.scm.branch == 'main' && 'true' || 'false' }}
